version: '3'

services:
  fe:
    container_name: fe
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/frontend
    ports:
      - "3000:3000"
    restart: unless-stopped