version: '3'

services:
  database:
    container_name: database
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydb
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./migration:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"
    restart: unless-stopped
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    depends_on:
      - database